title: Angela Deslandes # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  US Navy Veteran admist a career change, seeking an entry level position as a Data Analyst.
  <br><br>
  BA Degree in Computer Science <br>
  <i>University of Rhode Island</i> 12/23
  <br><br>
  Google Data Analytics Professional Certificate | <i>Coursera</i> 12/23
  <br><br>
  Data Analytics Certificate
  <br>
  <i>Thinkful</i> 08/23
  <br><br>
  <a href="https://www.linkedin.com/in/angela-deslandes/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-BSS448T218 # your Google Analytics tracking ID here
