title: Angela Deslandes # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  US Navy Veteran admist a career change, seeking an entry level position as a Data Analyst.
  <br><br>
  BA Degree in Computer Science <br>
  University of Rhode Island 12/23
  <br><br>
  Google Data Analytics Professional Certificate | Coursera 12/23
  <br><br>
  Completed Data Analyst Immersion
  <br>
  Thinkful 08/23
  <br><br>
  <a href="https://www.linkedin.com/in/angela-deslandes/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-BSS448T218 # your Google Analytics tracking ID here
