title: Angela Deslandes # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  US Navy Veteran admist a career change, seeking an entry level position as a Data Analyst.
  <br><br>
  Completed a Bachelor's Degree in Computer Science from the University of Rhode Island.
  <br><br>
  <a href="https://www.linkedin.com/in/angela-deslandes/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-BSS448T218 # your Google Analytics tracking ID here
